
services:
  user-service:
    build:
      context: ./service-user
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./service-user/.env
    depends_on:
      - mysql

  auth-service:
    build:
      context: ./service-auth
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./service-auth/.env
    depends_on:
      - mysql

  events-service:
    build:
      context: ./service-events
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - ./service-events/.env
    depends_on:
      - mysql

  api-gateway:
    build:
      context: ./service-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./service-gateway/.env

  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: tickets
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
