### Obter todos os eventos
GET http://localhost:3000/event/

### Obter evento por ID
GET http://localhost:3000/event/665924431bc437d4851f5681

### Adicionar um novo evento
POST http://localhost:3000/event/
Content-Type: application/json

{
  "title": "Evento Teste",
  "date": "2024-06-01T12:00:00.000Z",
  "description": "Descrição do evento teste",
  "capacity": 100,
  "category": "Categoria do Evento",
  "status": "Ativo",
  "location": "Expo SP",
  "cover": "teste",
  "price": 50
}

### Atualizar um evento existente
PATCH http://localhost:3000/event/665a0d0bb6409a4984e7ce07
Content-Type: application/json

{
  "title": "Novo Título do Evento",
  "date": "2024-06-01T12:00:00.000Z",
  "description": "Nova descrição do evento",
  "cover:": "teste",
  "price": 59
}

### Remover um evento
DELETE http://localhost:3000/event/665a0ca6b6409a4984e7cdf8
