### Obter todos os usuários
GET http://localhost:3000/user

### Obter usuário por ID
GET http://localhost:3000/user/6659cf243321ce436e7ec97d

### Adicionar um novo usuário
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "João da Silva",
  "email": "joao@example.com",
  "password": "senha123",
  "confirmPassword": "senha123",
  "CPF": "123.456.789-00",
  "phone": "(11) 99999-9999"
}

### Atualizar um usuário
PATCH http://localhost:3000/user/6659415da285c24e9542be12
Content-Type: application/json

{
  "name": "João da Silva Ramos",
  "email": "joao@example.com",
  "CPF": "123.456.789-00",
  "phone": "(11) 99999-9999"
}

### Remover um usuário
DELETE http://localhost:3000/user/6659178a4ff028ec73437f71

### Validar Usuário
POST http://localhost:3000/user/validate
Content-Type: application/json

{
  "email": "joao@example.com",
  "password": "senha123"
}
